version: "3.8"
services:
  app-dev:
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
     - ./src:/opt/app/src
    ports:
      - "8000:8000"
    restart: always
